### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by opdoll** [ProgPrak-Native-App/react-native-app#22]
A project README
We want a README in order to standardise our way of building and maintain a common theme throughout our app. In case we want to share the progress on our app to others, this would be a good starting point.

A README of our app would include:
- A small description of our project
- Description of building and publishing the app using Expo servers
- Description of building and distributing locally (eas build)
- Stylistic choices and color palette
- Whatever we may find useful in the future can be added here.. referencing future READMEs

**Comment by redstarmy** [comment]
Closed with #51
