### ISSUE TITLE
Account auf neues Gerät übertragen

### ISSUE THREAD

**Issue by MHajoha** [ProgPrak-Native-App/react-native-app#41]
Das Auth-Konzept (#40) macht einen "traditionellen" Login mit einem zuvor erstellten Account unmöglich, da Accounts nur durch einen AccountKey identifiziert werden, der eine vom BE generierte UUID enthält.

Um trotzdem mit mehreren Clients den selben Account verwenden zu können, bedarf es einer Methode, diesen AccountKey auf einen anderen Client zu übertragen. (Abtippen ist keine sinnvolle Lösung.) Im Falle von Übertragung in unsere App bietet sich ein QR-Code an.

Um aus diesem Feature den besten Nutzen zu schlagen, ist Abstimmung mit den anderen FE-Teams hilfreich, damit diese in ihren Web-Apps einen QR-Code des gleichen Formats anzeigen können.

## AC

* In der Profilseite kann sich ein QR-Code angezeigt werden lassen
* In der UserSetup-Komponente (Zweiter Screen beim ersten Start der App) gibt es statt "Done"-Button einen Button zum Erstellen eines neuen Accounts und einen zum Import
  * Beim Klick auf den letzteren wird ein QR-Code-Scanner geöffnet

## Out of Scope

* Wiederherstellung von verlorenen account keys / backup von account keys

**Comment by Sy-D** [comment]
Was passiert, wenn dieser verloren geht? Wie will man den Account zurückholen? Könnte man nicht ne  Cloud-Backup Funktion implementieren für den bisherigen Stand. Bezüglich Privacy Concerns - diesen dann mit dem Passwort versehen?
