### ISSUE TITLE
mid-term mock app

### ISSUE THREAD

**Issue by redstarmy** [ProgPrak-Native-App/react-native-app#46]
We want to create a presentable mock version of `develop` for demonstrating our progress at the mid-term (13.06). For this we want to replace all api data with actual meaningful data :) these changes would be pushed onto a separate mock branch (`demo/mid-term`) and never be merged.

**Comment by redstarmy** [comment]
Branch ist jetzt erstellt unter dem Namen `demo/mid-term`. Den branch zu verlinken habe ich leider nicht auf die schnelle geschafft :)

**Comment by MHajoha** [comment]
Letzten Endes wurde es der release channel [`default`](https://expo.dev/%40progprak_kopfsachen/kopfsachen?serviceType=classic&distribution=expo-go&releaseChannel=default)
