### ISSUE TITLE
Housekeeping 🧹

### ISSUE THREAD

**Issue by eliasgruenewald** [ProgPrak-Native-App/react-native-app#54]
Bitte entfernt alle _branches_, die nicht mehr benötigt werden, README aktualisieren usw.

**Comment by eliasgruenewald** [comment]
The new README looks great! :)

**Comment by redstarmy** [comment]
A README, contributing guide and code of conduct have been added with #51 to meet GH community standards.
Default issue templates have also been added with #52 for more organised future community issues.
Any unused branches have been removed along with cleaning up the project board :)

**Comment by eliasgruenewald** [comment]
![download](https://user-images.githubusercontent.com/18154624/175344900-b6c02cb1-501c-4d55-92f0-7d8f5792e9a8.png)
