### ISSUE TITLE
Sicherheitsnetz: Mehr als 6 Einträge

### ISSUE THREAD

**Issue by MHajoha** [ProgPrak-Native-App/react-native-app#68]
In dem originalen Design hat das Sicherheitsnetz nur 6 Knoten, daher können nur max. 6 Einträge erstellt werden. Möglicherweise wollen wir aber mehr erlauben.

**Comment by JonahBalshai** [comment]
Das hier ist im Sicherheitsnetz mit drin kann ich den Issue closen?
